version: '3.8'

name: 'rnft'

services:
  marketplace-service:
    build: ./marketplace-service
    ports:
      - "7000:8081"
    depends_on:
      - postgres
      - discovery-service
    environment:
      - PG_PASSWORD=${PG_PASSWORD}
      - JWT_SHARED_SECRET=${JWT_SHARED_SECRET}
      - PG_HOST=postgres
      - EUREKA_HOST=discovery-service
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
      - IPFS_API_AUTHORIZATION=${IPFS_API_AUTHORIZATION}
      - IPFS_API_URL=${IPFS_API_URL}
      - IPFS_GATEWAY=${IPFS_GATEWAY}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - RABBITMQ_HOST=rabbitmq
      - AES_PASSWORD=${AES_PASSWORD}
  api-gateway:
    build: ./api-gateway
    depends_on:
      - postgres
      - discovery-service
    environment:
      - PG_PASSWORD=${PG_PASSWORD}
      - MAIL_SMTP_HOST=${MAIL_SMTP_HOST}
      - MAIL_SMTP_PORT=${MAIL_SMTP_PORT}
      - MAIL_SMTP_USER=${MAIL_SMTP_USER}
      - MAIL_SMTP_FROM=${MAIL_SMTP_FROM}
      - MAIL_SMTP_PASSWORD=${MAIL_SMTP_PASSWORD}
      - JWT_GATEWAY_SECRET=${JWT_GATEWAY_SECRET}
      - JWT_SHARED_SECRET=${JWT_SHARED_SECRET}
      - PG_HOST=postgres
      - EUREKA_HOST=discovery-service
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
      - IPFS_API_AUTHORIZATION=${IPFS_API_AUTHORIZATION}
      - IPFS_API_URL=${IPFS_API_URL}
      - IPFS_GATEWAY=${IPFS_GATEWAY}
    ports:
      - "8080:8080"
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
  postgres:
    build: ./postgres
    volumes:
      - rnft_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}

volumes:
  rnft_db: {}
